---
# Updates web page on pushes to `master` as well as daily
name: webpage

on:
  schedule:
  # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  # run every day at 21:00 UTC
  - cron: "0 21 * * *"
  push:
    branches:
    - master

jobs:
  webpage:
    if: github.repository == 'aiidateam/aiida-registry'

    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR: Deploy Action
      COMMIT_AUTHOR_EMAIL: action@github.com
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install prerequisites
      run: pip install --upgrade wheel setuptools
    - name: Install
      run: pip install -e . -v
    - name: fetch metadata
      id: fetch_metadata
      run: aiida-registry fetch
    - name: make pages
      run: aiida-registry html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
